In [1]:
import sklearn

In [2]:
from sklearn.datasets import load_wine

In [3]:
import pandas as pd

In [4]:
wine = load_wine()

In [5]:
wine['data']

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [6]:
wine['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [7]:
wine_data = pd.DataFrame(wine['data'])

In [8]:
wine_data

0     1     2     3      4     5     6     7     8      9     10  \
0    14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29   5.64  1.04   
1    13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28   4.38  1.05   
2    13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81   5.68  1.03   
3    14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18   7.80  0.86   
4    13.24  2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82   4.32  1.04   
..     ...   ...   ...   ...    ...   ...   ...   ...   ...    ...   ...   
173  13.71  5.65  2.45  20.5   95.0  1.68  0.61  0.52  1.06   7.70  0.64   
174  13.40  3.91  2.48  23.0  102.0  1.80  0.75  0.43  1.41   7.30  0.70   
175  13.27  4.28  2.26  20.0  120.0  1.59  0.69  0.43  1.35  10.20  0.59   
176  13.17  2.59  2.37  20.0  120.0  1.65  0.68  0.53  1.46   9.30  0.60   
177  14.13  4.10  2.74  24.5   96.0  2.05  0.76  0.56  1.35   9.20  0.61   

       11      12  
0    3.92  1065.0  
1    3.40  1050.0  
2    3.17  1185.0  
3    3.45  1480.0  
4    2.93   735.0  
..    ...     ...  
173  1.74   740.0  
174  1.56   750.0  
175  1.56   835.0  
176  1.62   840.0  
177  1.60   560.0  

[178 rows x 13 columns]

In [9]:
wine_target = pd.DataFrame(wine['target'])

In [10]:
wine_target

0
0    0
1    0
2    0
3    0
4    0
..  ..
173  2
174  2
175  2
176  2
177  2

[178 rows x 1 columns]

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
dt = DecisionTreeClassifier()

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test = train_test_split(wine_data,wine_target,test_size=0.1)

In [15]:
x_train

0     1     2     3      4     5     6     7     8     9     10    11  \
104  12.51  1.73  1.98  20.5   85.0  2.20  1.92  0.32  1.48  2.94  1.04  3.57   
143  13.62  4.95  2.35  20.0   92.0  2.00  0.80  0.47  1.02  4.40  0.91  2.05   
10   14.10  2.16  2.30  18.0  105.0  2.95  3.32  0.22  2.38  5.75  1.25  3.17   
42   13.88  1.89  2.59  15.0  101.0  3.25  3.56  0.17  1.70  5.43  0.88  3.56   
149  13.08  3.90  2.36  21.5  113.0  1.41  1.39  0.34  1.14  9.40  0.57  1.33   
..     ...   ...   ...   ...    ...   ...   ...   ...   ...   ...   ...   ...   
124  11.87  4.31  2.39  21.0   82.0  2.86  3.03  0.21  2.91  2.80  0.75  3.64   
68   13.34  0.94  2.36  17.0  110.0  2.53  1.30  0.55  0.42  3.17  1.02  1.93   
125  12.07  2.16  2.17  21.0   85.0  2.60  2.65  0.37  1.35  2.76  0.86  3.28   
144  12.25  3.88  2.20  18.5  112.0  1.38  0.78  0.29  1.14  8.21  0.65  2.00   
31   13.58  1.66  2.36  19.1  106.0  2.86  3.19  0.22  1.95  6.90  1.09  2.88   

         12  
104   672.0  
143   550.0  
10   1510.0  
42   1095.0  
149   550.0  
..      ...  
124   380.0  
68    750.0  
125   378.0  
144   855.0  
31   1515.0  

[160 rows x 13 columns]

In [16]:
import pickle as pk

In [29]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [24]:
from sklearn.metrics import accuracy_score

In [31]:
y_pred = dt.predict(x_test)

In [32]:
accuracy_score(y_pred,y_test)

0.9444444444444444

In [33]:
y_pred

array([1, 0, 0, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2, 1, 2, 0, 0, 1])

In [34]:
pk.dump(dt,open('dt_model.pkl','wb'))

In [24]:
import numpy as np

In [27]:
dt.predict(np.array([100,100,100,100,100,100,100,100,100,100,100,100,100]).reshape(1,13))

array([0])

In [35]:
sklearn.__version__

'1.3.2'

In [2]:
sklearn.__version__

'1.4.1.post1'